# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: adf6f67539003b7afd24c693bdad90b6ba17cd17405b93ecfb6363c31fab19ef707eed00245e627ea4d43d8b0369f46003186cebd8500a53622a46a8a5ea2def

test:
  secret_key_base: 1244639cba71716f71d5f0af4b637127fa3f98500b769750bce542919aea96067921d6d1793338fb517b100e46df62f143b9231cb3d8405bc8f73843bc6aa5ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
